print("What is your Name")
Name=input()
print("what post are you applying for")
Post=input()
print("please supply your email_address")
Email_address=input()
print("please supply your Phone_number")
Phone_number=input()
print("please describe yourself")
Description=input()
print("why did you choose our company")
Reason=input()

print("These are my details:" + Name + "," + Post + "," + Email_address + "," + Phone_number + "," + Description + "," + Reason)