print("what did you buy from the market")
yam=input()
print("amount of yam")
yamamount=float(input())
print("enter your next item")
bread=input()
print("amount of bread")
breadamount=float(input())
print("other items that your bought")
cornflask=input()
print("amount of conflask")
conflaskamount=float(input())
print("this a my purchase details: yam: " + str(yamamount) + "bread: " + str(breadamount) + "cornflask: " + str(conflaskamount))